name: "rsync"
description: "Copy files to another host over a remote shell"
author: "domonda GmbH"

inputs:
  ssh-identity:
    description: "The SSH identity used to authenticate at the destination host"
    required: true
  from:
    description: "Workspace relative path from which you want to copy files from"
    required: true
  to:
    description: "Destination path including in the usual rsync format USER@HOST:DEST"
    required: true
  delete:
    description: "Delete extraneous files from destination"
  exclude:
    description: "Exclude files matching the pattern"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ssh-identity }}
    - ${{ inputs.from }}
    - ${{ inputs.to }}
    - ${{ inputs.delete }}
    - ${{ inputs.exclude }}
